package html

import (
	"testing"
)

func TestTags(t *testing.T) {

	tests := map[string]string{
		A("x").String():          "<a>x</a>",
		ABBR("x").String():       "<abbr>x</abbr>",
		ACRONYM("x").String():    "<acronym>x</acronym>",
		ADDRESS("x").String():    "<address>x</address>",
		AREA().String():          "<area />",
		ARTICLE("x").String():    "<article>x</article>",
		ASIDE("x").String():      "<aside>x</aside>",
		AUDIO("x").String():      "<audio>x</audio>",
		B("x").String():          "<b>x</b>",
		BASE().String():          "<base />",
		BDO("x").String():        "<bdo>x</bdo>",
		BDI("x").String():        "<bdi>x</bdi>",
		BIG("x").String():        "<big>x</big>",
		BLOCKQUOTE("x").String(): "<blockquote>x</blockquote>",
		BODY("x").String():       "<body>x</body>",
		BR().String():            "<br />",
		BUTTON("x").String():     "<button>x</button>",
		CANVAS("x").String():     "<canvas>x</canvas>",
		CAPTION("x").String():    "<caption>x</caption>",
		CITE("x").String():       "<cite>x</cite>",
		CODE("x").String():       "<code>x</code>",
		COL().String():           "<col />",
		COLGROUP("x").String():   "<colgroup>x</colgroup>",
		COMMAND().String():       "<command />",
		DATA("x").String():       "<data>x</data>",
		DATALIST("x").String():   "<datalist>x</datalist>",
		DD("x").String():         "<dd>x</dd>",
		DEL("x").String():        "<del>x</del>",
		DETAILS("x").String():    "<details>x</details>",
		DFN("x").String():        "<dfn>x</dfn>",
		DIV("x").String():        "<div>x</div>",
		DIALOG("x").String():     "<dialog>x</dialog>",
		DL("x").String():         "<dl>x</dl>",
		DT("x").String():         "<dt>x</dt>",
		EM("x").String():         "<em>x</em>",
		EMBED().String():         "<embed />",
		FIELDSET("x").String():   "<fieldset>x</fieldset>",
		FIGCAPTION("x").String(): "<figcaption>x</figcaption>",
		FIGURE("x").String():     "<figure>x</figure>",
		FOOTER("x").String():     "<footer>x</footer>",
		FORM("x").String():       "<form>x</form>",
		FRAME().String():         "<frame />",
		FRAMESET("x").String():   "<frameset>x</frameset>",
		H(7, "x").String():       "<h7>x</h7>",
		H1("x").String():         "<h1>x</h1>",
		H2("x").String():         "<h2>x</h2>",
		H3("x").String():         "<h3>x</h3>",
		H4("x").String():         "<h4>x</h4>",
		H5("x").String():         "<h5>x</h5>",
		H6("x").String():         "<h6>x</h6>",
		HEAD("x").String():       "<head>x</head>",
		HEADER("x").String():     "<header>x</header>",
		HGROUP("x").String():     "<hgroup>x</hgroup>",
		HR().String():            "<hr />",
		HTML("x").String():       "<html>x</html>",
		I("x").String():          "<i>x</i>",
		IFRAME().String():        "<iframe />",
		IMG().String():           "<img />",
		INPUT().String():         "<input />",
		INS("x").String():        "<ins>x</ins>",
		KBD("x").String():        "<kbd>x</kbd>",
		KEYGEN().String():        "<keygen />",
		LABEL("x").String():      "<label>x</label>",
		LEGEND("x").String():     "<legend>x</legend>",
		LI("x").String():         "<li>x</li>",
		LINK().String():          "<link />",
		MAP("x").String():        "<map>x</map>",
		MATH("x").String():       "<math>x</math>",
		MENU("x").String():       "<menu>x</menu>",
		META().String():          "<meta />",
		METER("x").String():      "<meter>x</meter>",
		NAV("x").String():        "<nav>x</nav>",
		NOFRAMES("x").String():   "<noframes>x</noframes>",
		NOSCRIPT("x").String():   "<noscript>x</noscript>",
		OBJECT("x").String():     "<object>x</object>",
		OL("x").String():         "<ol>x</ol>",
		OPTGROUP("x").String():   "<optgroup>x</optgroup>",
		OPTION("x").String():     "<option>x</option>",
		OUTPUT("x").String():     "<output>x</output>",
		P("x").String():          "<p>x</p>",
		PARAM().String():         "<param />",
		PRE("x").String():        "<pre>x</pre>",
		PROGRESS("x").String():   "<progress>x</progress>",
		Q("x").String():          "<q>x</q>",
		RP("x").String():         "<rp>x</rp>",
		RT("x").String():         "<rt>x</rt>",
		RUBY("x").String():       "<ruby>x</ruby>",
		S("x").String():          "<s>x</s>",
		SAMP("x").String():       "<samp>x</samp>",
		SCRIPT("x").String():     "<script>x</script>",
		SECTION("x").String():    "<section>x</section>",
		MAIN("x").String():       "<main>x</main>",
		SELECT("x").String():     "<select>x</select>",
		SMALL("x").String():      "<small>x</small>",
		SOURCE("x").String():     "<source>x</source>",
		SPAN("x").String():       "<span>x</span>",
		STRONG("x").String():     "<strong>x</strong>",
		STYLE("x").String():      "<style>x</style>",
		SUB("x").String():        "<sub>x</sub>",
		SUMMARY("x").String():    "<summary>x</summary>",
		SUP("x").String():        "<sup>x</sup>",
		SVG("x").String():        "<svg>x</svg>",
		TABLE("x").String():      "<table>x</table>",
		TBODY("x").String():      "<tbody>x</tbody>",
		TD("x").String():         "<td>x</td>",
		TEXTAREA("x").String():   "<textarea>x</textarea>",
		TFOOT("x").String():      "<tfoot>x</tfoot>",
		TH("x").String():         "<th>x</th>",
		THEAD("x").String():      "<thead>x</thead>",
		TIME("x").String():       "<time>x</time>",
		TITLE("x").String():      "<title>x</title>",
		TR("x").String():         "<tr>x</tr>",
		TRACK().String():         "<track />",
		TT("x").String():         "<tt>x</tt>",
		U("x").String():          "<u>x</u>",
		UL("x").String():         "<ul>x</ul>",
		VAR("x").String():        "<var>x</var>",
		VIDEO("x").String():      "<video>x</video>",
		WBR().String():           "<wbr />",
	}

	for got, expected := range tests {
		if got != expected {
			t.Errorf("got: %#v expected: %#v", got, expected)
		}
	}

}
